# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stormlab/Nikita/coil_manipulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stormlab/Nikita/coil_manipulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stormlab/Nikita/coil_manipulator/CMakeFiles /home/stormlab/Nikita/coil_manipulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stormlab/Nikita/coil_manipulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named middleware_test

# Build rule for target.
middleware_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 middleware_test
.PHONY : middleware_test

# fast build rule for target.
middleware_test/fast:
	$(MAKE) -f CMakeFiles/middleware_test.dir/build.make CMakeFiles/middleware_test.dir/build
.PHONY : middleware_test/fast

#=============================================================================
# Target rules for targets named skeleton

# Build rule for target.
skeleton: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skeleton
.PHONY : skeleton

# fast build rule for target.
skeleton/fast:
	$(MAKE) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/build
.PHONY : skeleton/fast

#=============================================================================
# Target rules for targets named thcal

# Build rule for target.
thcal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thcal
.PHONY : thcal

# fast build rule for target.
thcal/fast:
	$(MAKE) -f CMakeFiles/thcal.dir/build.make CMakeFiles/thcal.dir/build
.PHONY : thcal/fast

#=============================================================================
# Target rules for targets named camera_test

# Build rule for target.
camera_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camera_test
.PHONY : camera_test

# fast build rule for target.
camera_test/fast:
	$(MAKE) -f CMakeFiles/camera_test.dir/build.make CMakeFiles/camera_test.dir/build
.PHONY : camera_test/fast

#=============================================================================
# Target rules for targets named run_camera

# Build rule for target.
run_camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_camera
.PHONY : run_camera

# fast build rule for target.
run_camera/fast:
	$(MAKE) -f CMakeFiles/run_camera.dir/build.make CMakeFiles/run_camera.dir/build
.PHONY : run_camera/fast

#=============================================================================
# Target rules for targets named precomps

# Build rule for target.
precomps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 precomps
.PHONY : precomps

# fast build rule for target.
precomps/fast:
	$(MAKE) -f CMakeFiles/precomps.dir/build.make CMakeFiles/precomps.dir/build
.PHONY : precomps/fast

#=============================================================================
# Target rules for targets named tip_tracking

# Build rule for target.
tip_tracking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tip_tracking
.PHONY : tip_tracking

# fast build rule for target.
tip_tracking/fast:
	$(MAKE) -f CMakeFiles/tip_tracking.dir/build.make CMakeFiles/tip_tracking.dir/build
.PHONY : tip_tracking/fast

#=============================================================================
# Target rules for targets named field3d

# Build rule for target.
field3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 field3d
.PHONY : field3d

# fast build rule for target.
field3d/fast:
	$(MAKE) -f CMakeFiles/field3d.dir/build.make CMakeFiles/field3d.dir/build
.PHONY : field3d/fast

#=============================================================================
# Target rules for targets named introducer

# Build rule for target.
introducer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 introducer
.PHONY : introducer

# fast build rule for target.
introducer/fast:
	$(MAKE) -f CMakeFiles/introducer.dir/build.make CMakeFiles/introducer.dir/build
.PHONY : introducer/fast

#=============================================================================
# Target rules for targets named nikita_cl

# Build rule for target.
nikita_cl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nikita_cl
.PHONY : nikita_cl

# fast build rule for target.
nikita_cl/fast:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/build
.PHONY : nikita_cl/fast

#=============================================================================
# Target rules for targets named HCoilMiddlewareLib

# Build rule for target.
HCoilMiddlewareLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HCoilMiddlewareLib
.PHONY : HCoilMiddlewareLib

# fast build rule for target.
HCoilMiddlewareLib/fast:
	$(MAKE) -f libs/src/CMakeFiles/HCoilMiddlewareLib.dir/build.make libs/src/CMakeFiles/HCoilMiddlewareLib.dir/build
.PHONY : HCoilMiddlewareLib/fast

#=============================================================================
# Target rules for targets named LakeshoreF71Lib

# Build rule for target.
LakeshoreF71Lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LakeshoreF71Lib
.PHONY : LakeshoreF71Lib

# fast build rule for target.
LakeshoreF71Lib/fast:
	$(MAKE) -f libs/src/CMakeFiles/LakeshoreF71Lib.dir/build.make libs/src/CMakeFiles/LakeshoreF71Lib.dir/build
.PHONY : LakeshoreF71Lib/fast

#=============================================================================
# Target rules for targets named LinActuatorLib

# Build rule for target.
LinActuatorLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinActuatorLib
.PHONY : LinActuatorLib

# fast build rule for target.
LinActuatorLib/fast:
	$(MAKE) -f libs/src/CMakeFiles/LinActuatorLib.dir/build.make libs/src/CMakeFiles/LinActuatorLib.dir/build
.PHONY : LinActuatorLib/fast

#=============================================================================
# Target rules for targets named DxkdpLib

# Build rule for target.
DxkdpLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DxkdpLib
.PHONY : DxkdpLib

# fast build rule for target.
DxkdpLib/fast:
	$(MAKE) -f libs/src/CMakeFiles/DxkdpLib.dir/build.make libs/src/CMakeFiles/DxkdpLib.dir/build
.PHONY : DxkdpLib/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f submodules/a-star/CMakeFiles/main.dir/build.make submodules/a-star/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named a-star

# Build rule for target.
a-star: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a-star
.PHONY : a-star

# fast build rule for target.
a-star/fast:
	$(MAKE) -f submodules/a-star/CMakeFiles/a-star.dir/build.make submodules/a-star/CMakeFiles/a-star.dir/build
.PHONY : a-star/fast

#=============================================================================
# Target rules for targets named Doxygen

# Build rule for target.
Doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Doxygen
.PHONY : Doxygen

# fast build rule for target.
Doxygen/fast:
	$(MAKE) -f docsBuild/CMakeFiles/Doxygen.dir/build.make docsBuild/CMakeFiles/Doxygen.dir/build
.PHONY : Doxygen/fast

dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.o: dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.o

.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.o

# target to build an object file
dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.o:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.o
.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.o

dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.i: dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.i

.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.i

# target to preprocess a source file
dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.i:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.i
.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.i

dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.s: dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.s

.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.s

# target to generate assembly for a file
dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.s:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.s
.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.cpp.s

dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.o: dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.o

.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.o

# target to build an object file
dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.o:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.o
.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.o

dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.i: dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.i

.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.i

# target to preprocess a source file
dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.i:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.i
.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.i

dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.s: dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.s

.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.s

# target to generate assembly for a file
dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.s:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.s
.PHONY : dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.cpp.s

dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.o: dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.o

.PHONY : dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.o

# target to build an object file
dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.o:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.o
.PHONY : dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.o

dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.i: dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.i

.PHONY : dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.i

# target to preprocess a source file
dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.i:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.i
.PHONY : dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.i

dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.s: dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.s

.PHONY : dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.s

# target to generate assembly for a file
dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.s:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.s
.PHONY : dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.c.s

src/introducer.o: src/introducer.cpp.o

.PHONY : src/introducer.o

# target to build an object file
src/introducer.cpp.o:
	$(MAKE) -f CMakeFiles/introducer.dir/build.make CMakeFiles/introducer.dir/src/introducer.cpp.o
.PHONY : src/introducer.cpp.o

src/introducer.i: src/introducer.cpp.i

.PHONY : src/introducer.i

# target to preprocess a source file
src/introducer.cpp.i:
	$(MAKE) -f CMakeFiles/introducer.dir/build.make CMakeFiles/introducer.dir/src/introducer.cpp.i
.PHONY : src/introducer.cpp.i

src/introducer.s: src/introducer.cpp.s

.PHONY : src/introducer.s

# target to generate assembly for a file
src/introducer.cpp.s:
	$(MAKE) -f CMakeFiles/introducer.dir/build.make CMakeFiles/introducer.dir/src/introducer.cpp.s
.PHONY : src/introducer.cpp.s

src/middleware_test.o: src/middleware_test.cpp.o

.PHONY : src/middleware_test.o

# target to build an object file
src/middleware_test.cpp.o:
	$(MAKE) -f CMakeFiles/middleware_test.dir/build.make CMakeFiles/middleware_test.dir/src/middleware_test.cpp.o
.PHONY : src/middleware_test.cpp.o

src/middleware_test.i: src/middleware_test.cpp.i

.PHONY : src/middleware_test.i

# target to preprocess a source file
src/middleware_test.cpp.i:
	$(MAKE) -f CMakeFiles/middleware_test.dir/build.make CMakeFiles/middleware_test.dir/src/middleware_test.cpp.i
.PHONY : src/middleware_test.cpp.i

src/middleware_test.s: src/middleware_test.cpp.s

.PHONY : src/middleware_test.s

# target to generate assembly for a file
src/middleware_test.cpp.s:
	$(MAKE) -f CMakeFiles/middleware_test.dir/build.make CMakeFiles/middleware_test.dir/src/middleware_test.cpp.s
.PHONY : src/middleware_test.cpp.s

src/nikita_cl.o: src/nikita_cl.cpp.o

.PHONY : src/nikita_cl.o

# target to build an object file
src/nikita_cl.cpp.o:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/src/nikita_cl.cpp.o
.PHONY : src/nikita_cl.cpp.o

src/nikita_cl.i: src/nikita_cl.cpp.i

.PHONY : src/nikita_cl.i

# target to preprocess a source file
src/nikita_cl.cpp.i:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/src/nikita_cl.cpp.i
.PHONY : src/nikita_cl.cpp.i

src/nikita_cl.s: src/nikita_cl.cpp.s

.PHONY : src/nikita_cl.s

# target to generate assembly for a file
src/nikita_cl.cpp.s:
	$(MAKE) -f CMakeFiles/nikita_cl.dir/build.make CMakeFiles/nikita_cl.dir/src/nikita_cl.cpp.s
.PHONY : src/nikita_cl.cpp.s

src/opencv/camera_test.o: src/opencv/camera_test.cpp.o

.PHONY : src/opencv/camera_test.o

# target to build an object file
src/opencv/camera_test.cpp.o:
	$(MAKE) -f CMakeFiles/camera_test.dir/build.make CMakeFiles/camera_test.dir/src/opencv/camera_test.cpp.o
.PHONY : src/opencv/camera_test.cpp.o

src/opencv/camera_test.i: src/opencv/camera_test.cpp.i

.PHONY : src/opencv/camera_test.i

# target to preprocess a source file
src/opencv/camera_test.cpp.i:
	$(MAKE) -f CMakeFiles/camera_test.dir/build.make CMakeFiles/camera_test.dir/src/opencv/camera_test.cpp.i
.PHONY : src/opencv/camera_test.cpp.i

src/opencv/camera_test.s: src/opencv/camera_test.cpp.s

.PHONY : src/opencv/camera_test.s

# target to generate assembly for a file
src/opencv/camera_test.cpp.s:
	$(MAKE) -f CMakeFiles/camera_test.dir/build.make CMakeFiles/camera_test.dir/src/opencv/camera_test.cpp.s
.PHONY : src/opencv/camera_test.cpp.s

src/opencv/run_camera.o: src/opencv/run_camera.cpp.o

.PHONY : src/opencv/run_camera.o

# target to build an object file
src/opencv/run_camera.cpp.o:
	$(MAKE) -f CMakeFiles/run_camera.dir/build.make CMakeFiles/run_camera.dir/src/opencv/run_camera.cpp.o
.PHONY : src/opencv/run_camera.cpp.o

src/opencv/run_camera.i: src/opencv/run_camera.cpp.i

.PHONY : src/opencv/run_camera.i

# target to preprocess a source file
src/opencv/run_camera.cpp.i:
	$(MAKE) -f CMakeFiles/run_camera.dir/build.make CMakeFiles/run_camera.dir/src/opencv/run_camera.cpp.i
.PHONY : src/opencv/run_camera.cpp.i

src/opencv/run_camera.s: src/opencv/run_camera.cpp.s

.PHONY : src/opencv/run_camera.s

# target to generate assembly for a file
src/opencv/run_camera.cpp.s:
	$(MAKE) -f CMakeFiles/run_camera.dir/build.make CMakeFiles/run_camera.dir/src/opencv/run_camera.cpp.s
.PHONY : src/opencv/run_camera.cpp.s

src/opencv/skeleton_method.o: src/opencv/skeleton_method.cpp.o

.PHONY : src/opencv/skeleton_method.o

# target to build an object file
src/opencv/skeleton_method.cpp.o:
	$(MAKE) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/src/opencv/skeleton_method.cpp.o
.PHONY : src/opencv/skeleton_method.cpp.o

src/opencv/skeleton_method.i: src/opencv/skeleton_method.cpp.i

.PHONY : src/opencv/skeleton_method.i

# target to preprocess a source file
src/opencv/skeleton_method.cpp.i:
	$(MAKE) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/src/opencv/skeleton_method.cpp.i
.PHONY : src/opencv/skeleton_method.cpp.i

src/opencv/skeleton_method.s: src/opencv/skeleton_method.cpp.s

.PHONY : src/opencv/skeleton_method.s

# target to generate assembly for a file
src/opencv/skeleton_method.cpp.s:
	$(MAKE) -f CMakeFiles/skeleton.dir/build.make CMakeFiles/skeleton.dir/src/opencv/skeleton_method.cpp.s
.PHONY : src/opencv/skeleton_method.cpp.s

src/opencv/thresholds_cal.o: src/opencv/thresholds_cal.cpp.o

.PHONY : src/opencv/thresholds_cal.o

# target to build an object file
src/opencv/thresholds_cal.cpp.o:
	$(MAKE) -f CMakeFiles/thcal.dir/build.make CMakeFiles/thcal.dir/src/opencv/thresholds_cal.cpp.o
.PHONY : src/opencv/thresholds_cal.cpp.o

src/opencv/thresholds_cal.i: src/opencv/thresholds_cal.cpp.i

.PHONY : src/opencv/thresholds_cal.i

# target to preprocess a source file
src/opencv/thresholds_cal.cpp.i:
	$(MAKE) -f CMakeFiles/thcal.dir/build.make CMakeFiles/thcal.dir/src/opencv/thresholds_cal.cpp.i
.PHONY : src/opencv/thresholds_cal.cpp.i

src/opencv/thresholds_cal.s: src/opencv/thresholds_cal.cpp.s

.PHONY : src/opencv/thresholds_cal.s

# target to generate assembly for a file
src/opencv/thresholds_cal.cpp.s:
	$(MAKE) -f CMakeFiles/thcal.dir/build.make CMakeFiles/thcal.dir/src/opencv/thresholds_cal.cpp.s
.PHONY : src/opencv/thresholds_cal.cpp.s

src/opencv/tip_tracking.o: src/opencv/tip_tracking.cpp.o

.PHONY : src/opencv/tip_tracking.o

# target to build an object file
src/opencv/tip_tracking.cpp.o:
	$(MAKE) -f CMakeFiles/tip_tracking.dir/build.make CMakeFiles/tip_tracking.dir/src/opencv/tip_tracking.cpp.o
.PHONY : src/opencv/tip_tracking.cpp.o

src/opencv/tip_tracking.i: src/opencv/tip_tracking.cpp.i

.PHONY : src/opencv/tip_tracking.i

# target to preprocess a source file
src/opencv/tip_tracking.cpp.i:
	$(MAKE) -f CMakeFiles/tip_tracking.dir/build.make CMakeFiles/tip_tracking.dir/src/opencv/tip_tracking.cpp.i
.PHONY : src/opencv/tip_tracking.cpp.i

src/opencv/tip_tracking.s: src/opencv/tip_tracking.cpp.s

.PHONY : src/opencv/tip_tracking.s

# target to generate assembly for a file
src/opencv/tip_tracking.cpp.s:
	$(MAKE) -f CMakeFiles/tip_tracking.dir/build.make CMakeFiles/tip_tracking.dir/src/opencv/tip_tracking.cpp.s
.PHONY : src/opencv/tip_tracking.cpp.s

src/precomputation.o: src/precomputation.cpp.o

.PHONY : src/precomputation.o

# target to build an object file
src/precomputation.cpp.o:
	$(MAKE) -f CMakeFiles/precomps.dir/build.make CMakeFiles/precomps.dir/src/precomputation.cpp.o
.PHONY : src/precomputation.cpp.o

src/precomputation.i: src/precomputation.cpp.i

.PHONY : src/precomputation.i

# target to preprocess a source file
src/precomputation.cpp.i:
	$(MAKE) -f CMakeFiles/precomps.dir/build.make CMakeFiles/precomps.dir/src/precomputation.cpp.i
.PHONY : src/precomputation.cpp.i

src/precomputation.s: src/precomputation.cpp.s

.PHONY : src/precomputation.s

# target to generate assembly for a file
src/precomputation.cpp.s:
	$(MAKE) -f CMakeFiles/precomps.dir/build.make CMakeFiles/precomps.dir/src/precomputation.cpp.s
.PHONY : src/precomputation.cpp.s

src/set3DField.o: src/set3DField.cpp.o

.PHONY : src/set3DField.o

# target to build an object file
src/set3DField.cpp.o:
	$(MAKE) -f CMakeFiles/field3d.dir/build.make CMakeFiles/field3d.dir/src/set3DField.cpp.o
.PHONY : src/set3DField.cpp.o

src/set3DField.i: src/set3DField.cpp.i

.PHONY : src/set3DField.i

# target to preprocess a source file
src/set3DField.cpp.i:
	$(MAKE) -f CMakeFiles/field3d.dir/build.make CMakeFiles/field3d.dir/src/set3DField.cpp.i
.PHONY : src/set3DField.cpp.i

src/set3DField.s: src/set3DField.cpp.s

.PHONY : src/set3DField.s

# target to generate assembly for a file
src/set3DField.cpp.s:
	$(MAKE) -f CMakeFiles/field3d.dir/build.make CMakeFiles/field3d.dir/src/set3DField.cpp.s
.PHONY : src/set3DField.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... middleware_test"
	@echo "... skeleton"
	@echo "... thcal"
	@echo "... camera_test"
	@echo "... run_camera"
	@echo "... precomps"
	@echo "... tip_tracking"
	@echo "... field3d"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... introducer"
	@echo "... nikita_cl"
	@echo "... HCoilMiddlewareLib"
	@echo "... LakeshoreF71Lib"
	@echo "... LinActuatorLib"
	@echo "... DxkdpLib"
	@echo "... main"
	@echo "... a-star"
	@echo "... Doxygen"
	@echo "... dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.o"
	@echo "... dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.i"
	@echo "... dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed.s"
	@echo "... dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.o"
	@echo "... dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.i"
	@echo "... dynamic_lungs_embed/4_DynamicLungs_working/dynamic_lungs_embed_ert_rtw/dynamic_lungs_embed_data.s"
	@echo "... dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.o"
	@echo "... dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.i"
	@echo "... dynamic_lungs_embed/MATLAB/rtw/c/src/rt_logging.s"
	@echo "... src/introducer.o"
	@echo "... src/introducer.i"
	@echo "... src/introducer.s"
	@echo "... src/middleware_test.o"
	@echo "... src/middleware_test.i"
	@echo "... src/middleware_test.s"
	@echo "... src/nikita_cl.o"
	@echo "... src/nikita_cl.i"
	@echo "... src/nikita_cl.s"
	@echo "... src/opencv/camera_test.o"
	@echo "... src/opencv/camera_test.i"
	@echo "... src/opencv/camera_test.s"
	@echo "... src/opencv/run_camera.o"
	@echo "... src/opencv/run_camera.i"
	@echo "... src/opencv/run_camera.s"
	@echo "... src/opencv/skeleton_method.o"
	@echo "... src/opencv/skeleton_method.i"
	@echo "... src/opencv/skeleton_method.s"
	@echo "... src/opencv/thresholds_cal.o"
	@echo "... src/opencv/thresholds_cal.i"
	@echo "... src/opencv/thresholds_cal.s"
	@echo "... src/opencv/tip_tracking.o"
	@echo "... src/opencv/tip_tracking.i"
	@echo "... src/opencv/tip_tracking.s"
	@echo "... src/precomputation.o"
	@echo "... src/precomputation.i"
	@echo "... src/precomputation.s"
	@echo "... src/set3DField.o"
	@echo "... src/set3DField.i"
	@echo "... src/set3DField.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

